name: Photostock Actions
run-name: testing PR
on:
  pull_request:
    branches: ["main"]
  merge_group:
    types: [checks_requested]
jobs:
  code-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter from stable branch
        if: ${{ inputs.FLUTTER_VERSION == '' }}
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format -o none --set-exit-if-changed ./lib/

      - name: Check lints
        run: dart analyze ./lib/

      - name: Run tests
        run: flutter test

